import { EOL } from "os";
import * as assert from "assert";
import transformer from "../../../src/core/transformer/ios";

describe("iOSTransformer.transformComment", () => {
  it("transforms comment", () => {
    const result = transformer.transformComment("un commentaire");

    assert.strictEqual("// un commentaire", result);
  });
});

describe("iOSTransformer.transformKeyValue", () => {
  it("transforms key value", () => {
    const line = transformer.transformKeyValue("ma_cle", "La valeur");
    assert.strictEqual('"ma_cle" = "La valeur";', line);
  });

  it("escapes quote", () => {
    const line = transformer.transformKeyValue("ma_cle", 'La "valeur"');
    assert.strictEqual('"ma_cle" = "La \\"valeur\\"";', line);
  });
});

describe("iOSTransformer.insert", () => {
  it("should insert after when not empty", () => {
    const result = transformer.insert(
      "// header" + EOL + '"aa" = "bb";' + EOL,
      "à insérer"
    );
    assert.strictEqual(
      "// header" +
        EOL +
        '"aa" = "bb";' +
        EOL +
        transformer.AUTOGENERATED_TAG +
        EOL +
        "à insérer",
      result
    );
  });

  it("should replace it when has auto generate tag should", () => {
    const result = transformer.insert(
      "// header" + EOL + transformer.AUTOGENERATED_TAG + EOL + "à effacer",
      "à insérer"
    );
    assert.strictEqual(
      "// header" + EOL + transformer.AUTOGENERATED_TAG + EOL + "à insérer",
      result
    );
  });

  it("should insert after same as before if new value doesnt change", () => {
    const before =
      "// header" + EOL + transformer.AUTOGENERATED_TAG + EOL + "before";
    const result = transformer.insert(before, "before");
    assert.strictEqual(before, result);
  });
});
