export interface Transformer {
  transformComment(comment: string): string;
  transformKeyValue(key: string, value: string): string;
  /* merge newValues dans input selon la convention de la plateforme (utilisation d'un commentaire pour séparer ce qui est généré */
  insert(input, newValues, options?: {[key: string]: any}): string;
  transformPluralsValues?(key: string, values): string;
  AUTOGENERATED_TAG?: string;
}
